### ISSUE TITLE
It breaks Youtube

### ISSUE THREAD

**Issue by krischen62** [yzyhk904/hifi-maximizer-mod#1]
When I flashed this magisk module and rebooted my phone, only youtube with problem - I can open youtube but cannot show content. I just saw the loading circle keeps running and running. So I disable this module in magisk manager and Youtube works normally.

Is it because of my ROM is android 13 and it magisk module is outdated and no support for android 13 ?

**Comment by yzyhk904** [comment]
This was reproduced on A12 & A13 devices both. The cause is the camera service stopped by the magisk module. I don't know why Youtube app needs the camera service, but you can use the magisk module if you set `DisableCameraService="no"` in "service.sh" in its zip file and install the modified file again.

If you care the audio quality loss by enabling the camera service, try [USB_SampleRate_Changer](https://github.com/yzyhk904/USB_SampleRate_Changer). This includes "extras/jitter-reducer.sh" that is a flexible script version of the above module. See its Readme in details.
