### ISSUE TITLE
Phone Hangs

### ISSUE THREAD

**Issue by 4adbfa76** [yzyhk904/hifi-maximizer-mod#10]
Phone hangs when module is installed. It becomes unusable and system ui crashes continuously.

**Comment by yzyhk904** [comment]
What device are you using? Some devices, especially audio enhanced tablets may crash an AV settings app because they don't check existence of the system wide effects framework that the module has disabled.

Can you use other functions of the device without effectors (equalizers, base boosters, virtualizers, etc) including echo cancelers and automatic gain control that phone apps usually use?

**Comment by 4adbfa76** [comment]
Device specs: https://www.gsmarena.com/tecno_spark_4-10695.php

The sound became great as i decided to use your module Audio Misc Settings with no hanging but being a music lover i want to have better experience but HIFI Maximizer makes the phone to hang and the System UI continues to crash.

**Comment by yzyhk904** [comment]
Proprietary special battery savors on your device or something may cause such a crash? I don't have any idea now.

"Hifi-maximizer" consists mainly of "audio-misc-settings" and "jitter-reducer.sh" in "USB_SampleRate_Changer". You can use "jitter-reducer.sh" on the fly with some options except causing the crash after booting with "audio-misc-settings". "jitter-reducer.sh" can switch "on" and "off" of each option (each jitter-reducing feature) on the fly, so you would find the cause of the crash.
