### ISSUE TITLE
Some Setting crash after install the module

### ISSUE THREAD

**Issue by ilkafrv** [yzyhk904/hifi-maximizer-mod#18]
Hi,
I installed this module on
 - Google Pixel 4xl
 - Running crDroid Android v10.5 for Google Pixel 4XL (coral).
 - NikGapps installed
 
 But after install, when I tried to click
  - Settings -> Accessibility -> auto close the Setting window + nothing happen.
  - crDroid Settings -> NAVIGATION -> error = Settings keeps stopping ...
  
  Really want to run your module without those issues. Could you help ?

**Comment by ilkafrv** [comment]
I know it caused the problem because disable the mod -> restart -> make those problems went away!

**Comment by yzyhk904** [comment]
I can reproduce the first one, but cannot the second one on crDroid 10.5 here (not Pixel 4XL).

The cause of the former is crDroid's bug triggered by disabling "Camera Server". You can avoid this situation by editing an archive of this module. See README.md.

I guess the second one happens on crDroid & Pixel 4XL only. Till now, I've never heard such a thing on any device and any ROM.

Can you install my other module ["Audio Misc. Settings"](https://github.com/Magisk-Modules-Alt-Repo/audio-misc-settings) instead of "Hifi Maximizer"? If this changes the situation, I can get more info.

**Comment by ilkafrv** [comment]
I changed

EnableCameraService="no"

to

EnableCameraService="yes"

on service.sh and remove exists module and replace with the mod one and both two problems above disappear!

Not try the module "Audio Misc. Settings" yet!

**Comment by yzyhk904** [comment]
You don't need to install "Audio Misc. Settings". I understand they are caused by ROM's bugs trigged by disabling "Camera Server".
