### ISSUE TITLE
JamesDSP stopped working. Only 15 out of 100 volume steps working.

### ISSUE THREAD

**Issue by jyuuren** [yzyhk904/hifi-maximizer-mod#2]
Device that i use: Xiaomi 11T.
Also when digital volume maxed out, distortion occurs. This is not case with analog volume on my dac, so its not headphone or dac related BUT i sense this distortion without this module and can't confirm if this issue also occurs with this module because i can't use JamesDSP to EQ my headphone to boost low-ends which where distortion gets senseable.

**Comment by yzyhk904** [comment]
Please read README. You cannot use any equalizers, virtualizers and also visualizers with this module because it disables the effect framework itself interfacing to system wide equalizers, etc. for reducing jitter distortion on all digital outputs. I think that the best equalizing for hi-fi audio is disabling the effect framework itself (and if you find something wrong in music sources themselves, use an in-app equalizer).

I think your equalizer distorts output sound by clipping over 0dB level. Have you lowered the gain in JamesDSP yet?
