### ISSUE TITLE
Revert all changes

### ISSUE THREAD

**Issue by yabo-boye** [yzyhk904/hifi-maximizer-mod#24]
What this module does to audio quality is quite impressive,  however I am not ready to sacrifice security,  camera or battery life as this device is also mg daily driver.

I tried both disabling and removing the module but I couldnt get jamesdso and dolby back to work for causal listening. 

How can I effectively uninstall this? 

I could see a scenario where I could use this when I need more serious listening and disable it for other uses of the device.

Is this possible at all?

**Comment by yzyhk904** [comment]
What did you actually do? If you simply removed this module and rebooted in the Magisk manager, you could revert to an original state.

Someone told me that he couldn't revert because of using a minor Magisk module manager app. Did you use the Magisk manager app directly?

I recommend you using [Audio Msic. Settings](https://github.com/Magisk-Modules-Alt-Repo/audio-misc-settings), [Audio Jitter Silencer](https://github.com/Magisk-Modules-Alt-Repo/audio-jitter-silencer), and [USB SampleRate Changer](https://github.com/yzyhk904/USB_SampleRate_Changer) including "extras/jitter-reducer.sh" which is the main component of this module.
