### ISSUE TITLE
Wavelet

### ISSUE THREAD

**Issue by Lycidias93** [yzyhk904/hifi-maximizer-mod#26]
Hello, 

On my pixel 6 pro with android 15 the Wavelet App doesn't detect any audio sessions, while this module is installed

**Comment by yzyhk904** [comment]
See README! 

I think disabling the effects framework is the best equalizing for Hi-Fi audio. The disadvantage of the framework is far more than the merit of the wavelet app.

Instead of the app, I recommend you using both of  my other modules "Audio Jitter Silencer" and "Resampling for Cheapies" (if using LDAC earphones or cheap DAC's) with this module together.
