### ISSUE TITLE
Issues with apps not opening

### ISSUE THREAD

**Issue by AnzacExodus** [yzyhk904/hifi-maximizer-mod#3]
Hi there, after installing the module using magisk, my YouTube app just keeps loading and no videos show also Chrome just opens and closes after a few seconds. Do you know what the issue may be and how it correlates to the mod?
I'm using the latest Evolution X rom on my Xiaomi mi 9. Cheers

**Comment by yzyhk904** [comment]
This is caused by disabling the camera server to reduce significant audio jitter. Youtube app needs the camera server when launching up for some unexplained reason.

If you like to avoid this situation, edit "service.sh" in the module zip file so that
DisableCameraService="yes". Then update (install over the existing one) with this modified one in the magisk manager and reboot.

Note: "DisableCameraService" means somehow "disabling camera service jitter redution".

**Comment by AnzacExodus** [comment]
Awesome, thanks for getting back, I'll give it a go and report back what happens, also thank you for the work you do with these audio mods!

**Comment by fillwithjoy1** [comment]
> This is caused by disabling the camera server to reduce significant audio jitter. Youtube app needs the camera server when launching up for some unexplained reason.
> 
> If you like to avoid this situation, edit "service.sh" in the module zip file so that DisableCameraService="yes". Then update (install over the existing one) with this modified one in the magisk manager and reboot.
> 
> Note: "DisableCameraService" means somehow "disabling camera service jitter redution".

hey just a question, does this mod drain my battery faster?

**Comment by yzyhk904** [comment]
> > This is caused by disabling the camera server to reduce significant audio jitter. Youtube app needs the camera server when launching up for some unexplained reason.
> > If you like to avoid this situation, edit "service.sh" in the module zip file so that DisableCameraService="yes". Then update (install over the existing one) with this modified one in the magisk manager and reboot.
> > Note: "DisableCameraService" means somehow "disabling camera service jitter redution".
> 
> hey just a question, does this mod drain my battery faster?

Make another issue, then I'll reply. This isn't related to the original one.
