### ISSUE TITLE
Audio over Google's USB-C DAC is static noise

### ISSUE THREAD

**Issue by JoshuaDoes** [yzyhk904/hifi-maximizer-mod#4]
Issue in the title, but the volume of the static noise is exactly the same even when one step above muted. Scared me a lot honestly :P 

Followed the install instructions to a tee, so not sure what the issue is. Audio works as expected when playing through my phone's speakers or through my Google Pixel Buds A-series over Bluetooth. I have installed and enabled Audio misc. settings, Hifi Maximizer, and USB Samplerate Unlocker. Prior to this, I was playing audio perfectly fine over the DAC with only USB Samplerate Unlocker (which I've had installed for ages now).

**Comment by yzyhk904** [comment]
I guess you use a DAC without 32bits integer format capability. Hifi-maximizer sets fixed 192kHz & 32bits integer output format (not usual automatic capability detection). This format is quite common nowadays, I think.

You can check this with "extras/alsa-hw-params.sh" in the USB_SampleRate_Changer. Or execute "USB_SampleRate_Changer.sh 48k 24". If so, edit "customize.sh" in the module zip file so that at line 94 and 95
                sRate="48000"
                aFormat="AUDIO_FORMAT_PCM_24_BIT_PACKED".
