### ISSUE TITLE
Removes all microphone filtering

### ISSUE THREAD

**Issue by madamunkey** [yzyhk904/hifi-maximizer-mod#6]
The app successfully makes all audio modes sound much better, but now the microphone picks up most audio being played, making calls cause extreme echo for the other people
On a Pixel 5a if that changes anything

**Comment by yzyhk904** [comment]
Please read the README carefully. This mod disables the effects framework itself interfacing with all effect modules including echo cancelers, automatic gain controls, equalizers, etc. because the framework makes large jitter and distorts audio outputs.

"Disabling the effects framework" is a main feature of this mod!

**Comment by madamunkey** [comment]
Dang , sorry for missing that

My goal for hd audio in call mode continues I guess!
